name: quimbi
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - blosc=1.17.0
  - bzip2=1.0.8
  - ca-certificates=2019.9.11
  - certifi=2019.9.11
  - freetype=2.10.0
  - hdf5=1.10.5
  - intel-openmp=2019.4
  - jpeg=9c
  - libblas=3.8.0
  - libcblas=3.8.0
  - liblapack=3.8.0
  - libpng=1.6.37
  - libtiff=4.1.0
  - lz4-c=1.8.3
  - mkl=2019.4
  - mock=3.0.5
  - numexpr=2.7.0
  - numpy=1.17.3
  - olefile=0.46
  - openssl=1.1.1d
  - pandas=0.25.3
  - pip=19.3.1
  - pytables=3.6.1
  - python=3.7.3
  - python-dateutil=2.8.1
  - pytz=2019.3
  - setuptools=41.6.0
  - six=1.13.0
  - sqlite=3.30.1
  - tk=8.6.9
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.4.3
  - pip:
    - pillow==6.2.1
#prefix: C:\Users\kwuellems\Anaconda3\envs\quimbi
